services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: meilisearch
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: finapus
    volumes:
      - meili_data:/meili_data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myapp
    restart: always
    ports:
      - "4003:4003"
    depends_on:
      meilisearch:
        condition: service_started
      redis:
        condition: service_started
    environment:
      - REDIS_URI=redis://redis:6379/
      - MONGO_URI=mongodb+srv://flickstar-dev:shokh%4012@flickstar-test.vap3yqj.mongodb.net/finapp-dev?retryWrites=true&w=majority
      - REDIS_EXPIRE_IN=900
      - REDIS_EXPIRE_IN_STATIC=86400
      - JWT_EXPIRE_IN=15m
      - JWT_REFRESH_EXPIRE_IN=7d
      - JWT_ACCESS_TOKEN_SECRET="access_token"
      - JWT_REFRESH_TOKEN_SECRET="refresh_token"
      - KAFKAJS_NO_PARTITIONER_WARNING=1
      - R2_ENDPOINT=https://e102025f2cc22eb4ab717992b480675b.r2.cloudflarestorage.com
      - R2_ACCESS_KEY_ID=1c556e8cd7ac71e84975f1a12a469779
      - R2_SECRET_ACCESS_KEY=54443861fdcbbb617b5c018639e47c9ce44a243cd7b1dcce881e4081193f7307
      - R2_REGION=auto
      - R2_BUCKET=test
      - R2_PUBLIC_URL=https://pub-301c1efdf41d428f9ab043c4d4ecbac9.r2.dev
      - GMAIL_USER=noreply@flickstar.net
      - GMAIL_PASSWORD=kD2QxSkxQjeJ
      - MASTER_OTP=123456
      - COOKIE_SECRET="Flickstar-Secret"
      - APP_VERSION=01
      - NODE_ENVIRONMENT=production
      - PROJECT_ENVIRONMENT=production
      - PORT=4003
      - IP_GEOLOCATOR_KEY=5b78e37cf8c2479a840d96a0bf978de1
      - MEILI_MASTER_KEY=finapus
      - MELLISSEARCH_HOST=http://meilisearch:7700  
      - DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks/1366503812273143880/thakQoGnLwo1WkjerlBSXqhUKuxPovIZCl4dZEP-aO4URhstp9NYN_fUDv9smu1I7avd
      - SWAGGER_HOSTED_URL=http://135.235.193.1:4003/api
      - AUTHENTIC_KEY_MSG91=454657AcRtfWsTFb68450accP1
      - TEMPLATE_ID_SIGNUP_MSG91=683f1a76d6fc056a6a5c8d05
      - TEMPLATE_ID_FORGET_PASSWORD_MSG91=6847b650d6fc051ec82a9689
      - TEMPLATE_ID_TWO_FACTOR_AUTH_MSG91=6847bafdd6fc0524f970e3f5
      - QR_EXPIRE_TIME=1d
      - REFERRAL_REFERRER_REWARD=5
      - REFERRAL_REFERRED_USER_REWARD=3
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - app


volumes:
  redis_data:
  meili_data:
  
