name: Continuous Integration Pipeline for Flickstar

on:
  push:
    branches:
      - main

jobs:
  deploy_main:
    runs-on: ubuntu-latest

    steps:
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Run remote command using password login
        run: |
          sshpass -p "${{ secrets.AZURE_SSH_PASSWORD }}" \
            ssh -o StrictHostKeyChecking=no azureadmin@4.213.171.49 \
            "bash ~/deploy3.sh"