name: Continuous Integration Pipeline for Flickstar

on:
  push:
    branches:
      - main

jobs:
  deploy_main:
    runs-on: ubuntu-latest

    steps:
      - name: Decode and set permissions for SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 -d > flickstarend-user.pem
          chmod 600 flickstarend-user.pem

      - name: Run remote command using SSH key
        run: |
          ssh -o StrictHostKeyChecking=no -i flickstarend-user.pem ubuntu@${{ secrets.SERVER_IP }} "bash ~/deploy.sh"
